AWSTemplateFormatVersion: "2010-09-09"

Resources:

 ImportExportS3Bucket:
  Type: "AWS::S3::Bucket"
  Properties:
   NotificationConfiguration:
     LambdaConfigurations:
       - 
         Event: "s3:ObjectCreated:*"
         Filter:
           S3Key: 
             Rules: 
               -
                 Name: "Suffix"
                 Value: "ova"
         Function: !GetAtt ImportOva.Arn
   AccessControl: "BucketOwnerFullControl"
   Tags:
    -
      Key: "Name"
      Value: !Join ["-", [Ref: "AWS::StackName", "s3", Ref: "AWS::Region"]]